routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/login', 'Admin\Auth\LoginController@showLoginForm')->name('/login');
Route::get('/', 'Admin\Auth\LoginController@showLoginForm')->name('/');
Route::post('/loggedin', 'Admin\Auth\LoginController@login');
Route::get('/password/reset', 'Admin\Auth\ForgotPasswordController@otpRequestForm')->name('password.reset');
Route::post('password/email', 'Admin\Auth\ForgotPasswordController@sendOTP')->name('password.email');
Route::get('password/otp', 'Admin\Auth\ForgotPasswordController@otpForm')->name('password.otp');
Route::get('password/otpvarify', 'Admin\Auth\ForgotPasswordController@otpVarification')->name('password.otpvarify');
Route::get('password/edit', 'Admin\Auth\ForgotPasswordController@passworUpdateForm')->name('password.edit');
Route::post('password/update', 'Admin\Auth\ForgotPasswordController@updatePassword')->name('password.update');

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {

	Route::post('logout', 'Auth\LoginController@logout')->name('logout');
	Route::resource('dashboard', 'Dashboard\DashboardController');

	Route::get('password', 'AdminController@password')->name('password');
	Route::post('password/update', 'AdminController@changePassword')->name('password.update');

	Route::get('profile', 'AdminController@profile')->name('profile');
	Route::post('profile/update', 'AdminController@profileUpdate')->name('profile.update');

	Route::resource('setting', 'Setting\SettingController');
	// Route::get('privacy/policy', 'Setting\SettingController@privacyPolicy')->name('privacy.policy');
	// Route::put('privacy-policy/update/{id}', 'Setting\SettingController@privacyPolicyUpdate')->name('privacy-policy.update');

	Route::resource('document', 'Document\DocumentController');
	Route::get('document/active/{id}', 'Document\DocumentController@changeStatus')->name('document.active');

	// Route::resource('service', 'Service\ServiceTypeController');

	// Route::resource('vehicle', 'Vehicle\VehicleController');
	// Route::post('vehicles','Vehicle\VehicleController@getVehicles')->name('dataProcessing');

	Route::resource('passenger', 'Passenger\PassengerController');
	Route::post('ajax-passenger','Passenger\PassengerController@ajaxPassenger')->name('ajax-passenger');

	Route::resource('driver', 'Driver\DriverController');
	Route::post('ajax-driver','Driver\DriverController@ajaxDriver')->name('ajax-driver');

	Route::get('drivers/document/{id}', 'Driver\DriverController@listDriverDocument')->name('drivers.document');
	// Route::get('drivers/service-type/{id}', 'Driver\DriverController@listDriverServiceType')->name('drivers.service-type');
	Route::get('driver/document/verification/{id}', 'Driver\DriverController@driverDocumentVerification')->name('driver.document.verification');
	Route::get('driver/activation/{id}', 'Driver\DriverController@driverActivationProcess')->name('driver.activation');
	// Route::get('driver/carimages/{id}', 'Driver\DriverController@driverCarImages')->name('driver.carimages');
	// Route::get('driver/transaction/{id}', 'Driver\DriverController@driverTransaction')->name('driver.transaction');
	// Route::post('driver/document-reason/{id}', 'Driver\DriverController@documentVerificationReason')->name('driver.document-reason');

	// Route::resource('credit', 'CreditPackage\CreditPackageController');
	// Route::resource('email-control', 'Email\EmailController');

	// //Driver Document verification.........

	// Route::get('driver/check-document/{id}', 'Driver\DocumentVerificationController@allDocumentCheck')->name('driver.check-document');
	// Route::get('driver/rating-review/{id}', 'Driver\DriverRatingController@driverRatingReview')->name('driver.rating-review');
	// Route::get('driver/runcron/{id}', 'Driver\DocumentVerificationController@cronjobToMailDriver')->name('driver.runcron');
	// //.....................................

	// Route::get('driver/rating-list/{id}/{last_id}/{first_id}', 'Driver\DriverRatingController@ratingList')->name('driver.rating-list');
	// Route::post('driver/reason/{id}', 'Driver\DriverController@driverInactiveBannedReason')->name('driver.reason');
	// Route::get('driver/rating-search/{id}', 'Driver\DriverRatingController@searchRating')->name('driver.rating-search');

	// Route::post('driver/rating-alert/{id}', 'Driver\DriverRatingController@driverRatingAlert')->name('driver.rating-alert');
	// //payment

	// Route::get('payment/index', 'Payment\PaymentController@paymentList')->name('payment.index');

	// Route::get('package/sales/report', 'PackageSales\PackageSalesReportController@packageSalesReport')->name('package.sales.report');
	// Route::get('package/sales/report/search', 'PackageSales\PackageSalesReportController@searchPackageSalesReport')->name('package.sales.report.search');
	// Route::get('package/sales/report/details/{id}', 'PackageSales\PackageSalesReportController@packageSalesReportDetails')->name('package.sales.report.details');
	// Route::get('package/sales/report/detail/{id}/{from_date}/{to_date}', 'PackageSales\PackageSalesReportController@packageSalesReportDetailsBySearch')->name('package.sales.report.detail');

	// //ride history
	// Route::get('statement/{type}', 'Statement\StatementController@statement')->name('statement');
	// 	//not use
	// 	Route::get('statement/today', 'Statement\StatementController@statement_today')->name('statement.today');
	// 	Route::get('statement/weekly', 'Statement\StatementController@statement_weekly')->name('statement.weekly');
	// 	Route::get('statement/monthly', 'Statement\StatementController@statement_monthly')->name('statement.monthly');
	// 	Route::get('statement/yearly', 'Statement\StatementController@statement_yearly')->name('statement.yearly');
	// 	//not use
	// Route::post('ajax-statement','Statement\StatementController@ajaxStatement')->name('ajax-statement');
	// //............

	// Route::get('statement/details/{id}/{param}', 'Statement\StatementController@rideDetails')->name('statement.details');

	// Route::get('statement/driver/index', 'Statement\StatementController@driverStatementIndex')->name('statement.driver.index');
	// Route::post('ajax-driver-statement','Statement\StatementController@ajaxDriverStatement')->name('ajax-driver-statement');

	// Route::get('statement/driver/details/{id}', 'Statement\StatementController@driverStatementDetails')->name('statement.driver.details');
	// Route::get('statement/driver/detailsbybid/{id}', 'Statement\StatementController@driverStatementDetailsByBid')->name('statement.driver.detailsbybid');
	
	// Route::resource('promocode', 'Promocode\PromocodeController');

	// Route::get('report-issue/bydriver', 'ReportIssue\ReportIssueController@reportedByDriver')->name('report-issue.bydriver');
	// Route::get('report-issue/bypassenger', 'ReportIssue\ReportIssueController@reportedByPassenger')->name('report-issue.bypassenger');
	// Route::get('report-issue/details/{id}/{param}', 'ReportIssue\ReportIssueController@reportIssueDetails')->name('report-issue.details');

	

});

resources/views/admin/include/footer.blade.php
<footer class="footer">
	<div class="container-fluid">
		<div class="row text-xs-center">
			<div class="col-sm-4 text-sm-left mb-0-5 mb-sm-0">
				<p>
                {{ App\Http\Controllers\Controller::setting()[4]->value }}
                </p>
			</div>
		</div>
	</div>
</footer>

resources/views/admin/include/header.blade.php
<!-- Header -->
<div class="site-header">
	<nav class="navbar navbar-light">
		<div class="navbar-left">
			<a class="navbar-brand" href="{{url('admin/dashboard')}}">
			<img class="image" src="{{URL::asset(App\Http\Controllers\Controller::setting()[1]->value)}}" style="height: 100%; width: 100%">
			</a>
			<div class="toggle-button dark sidebar-toggle-first float-xs-left hidden-md-up">
				<span class="hamburger"></span>
			</div>
			<div class="toggle-button-second dark float-xs-right hidden-md-up">
				<i class="ti-arrow-left"></i>
			</div>
			<div class="toggle-button dark float-xs-right hidden-md-up" data-toggle="collapse" data-target="#collapse-1">
				<span class="more"></span>
			</div>
		</div>
		<div class="navbar-right navbar-toggleable-sm collapse" id="collapse-1">
			<div class="toggle-button light sidebar-toggle-second float-xs-left hidden-sm-down">
				<span class="hamburger"></span>
			</div>

			<ul class="nav navbar-nav">
				<li class="nav-item hidden-sm-down">
					<a class="nav-link toggle-fullscreen" href="javascript:void(0)">
						<i class="ti-fullscreen"></i>
					</a>
				</li>
			</ul>
			<ul class="nav navbar-nav float-md-right">
				<li class="nav-item dropdown hidden-sm-down">
					<a href="#" data-toggle="dropdown" aria-expanded="false">
						{{App\Http\Controllers\Controller::adminProfile()->first_name}}
						<span class="avatar box-48">

						@if(isset(App\Http\Controllers\Controller::adminProfile()->picture))
	                    	@if(File::exists(storage_path('app/public' .str_replace("storage", "", App\Http\Controllers\Controller::adminProfile()->picture))))
                                <img src="{{URL::asset(App\Http\Controllers\Controller::adminProfile()->picture)}}" style="height: 100%;">
                            @else
                                <img src="{{URL::asset('main/avatar.jpg')}}">
                            @endif
	                   	@else
                     		<img src="{{URL::asset('main/avatar.jpg')}}">
	                    @endif
						</span>
					</a>
					<div class="dropdown-menu dropdown-menu-right animated fadeInUp">
						<a class="dropdown-item" href="{{route('admin.profile')}}">
							<i class="ti-user mr-0-5"></i> Profile
						</a>
						<a class="dropdown-item" href="{{route('admin.password')}}">
							<i class="ti-settings mr-0-5"></i> Change Password
						</a>
						<div class="dropdown-divider"></div>

						<a class="dropdown-item" href="{{ route('admin.logout') }}" onclick="event.preventDefault(); document.getElementById('logout_form').submit();">
							<i class="ti-power-off mr-0-5"></i> Sign out</a>
						<form id="logout_form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
                    	{{ csrf_field() }}
                		</form>

					</div>
				</li>
			</ul>

		</div>
	</nav>
</div>

resources/views/admin/include/nav.blade.php
<div class="site-sidebar">
	<div class="custom-scroll custom-scroll-light">
		<ul class="sidebar-menu">
			<li class="menu-title">Admin Dashboard</li>
			<li>
				<a href="{{ route('admin.dashboard.index') }}" class="waves-effect waves-light">
					<span class="s-icon"><i class="ti-anchor"></i></span>
					<span class="s-text">Dashboard</span>
				</a>
			</li>
			<!-- <li>
				<a href="{{-- {{ route('admin.dispatcher.index') }} --}}" class="waves-effect waves-light">
					<span class="s-icon"><i class="ti-target"></i></span>
					<span class="s-text">Dispatcher Panel</span>
				</a>
			</li> -->
			
			{{-- <li>
				<a href="{{ route('admin.heatmap') }}" class="waves-effect waves-light">
					<span class="s-icon"><i class="ti-map"></i></span>
					<span class="s-text">Heat Map</span>
				</a>
			</li> --}}
			
			<li class="menu-title">Members</li>
			<li class="with-sub">
				<a href="javascript:void(0)" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-crown"></i></span>
					<span class="s-text">Passengers</span>
				</a>
				<ul>
					<li><a href="{{ route('admin.passenger.index') }}">List Passengers</a></li>
					<li><a href="{{ route('admin.passenger.create') }}">Add New Passenger</a></li>
				</ul>
			</li>

			<li class="with-sub">
				<a href="javascript:void(0)" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-crown"></i></span>
					<span class="s-text">Drivers</span>
				</a>
				<ul>
					<li><a href="{{ route('admin.driver.index') }}">List Drivers</a></li>
					<li><a href="{{ route('admin.driver.create') }}">Add New Driver</a></li>
				</ul>
			</li>

			{{-- <li class="with-sub">
				<a href="#" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-crown"></i></span>
					<span class="s-text">Users</span>
				</a>
				<ul>
					<li><a href="{{ route('admin.user.index') }}">List Users</a></li>
					<li><a href="{{ route('admin.user.create') }}">Add New User</a></li>
				</ul>
			</li> --}}
			{{-- <li class="with-sub">
				<a href="#" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-car"></i></span>
					<span class="s-text">Providers</span>
				</a>
				<ul>
					<li><a href="{{ route('admin.provider.index') }}">List Providers</a></li>
					<li><a href="{{ route('admin.provider.create') }}">Add New Provider</a></li>
				</ul>
			</li> --}}
			<!-- <li class="with-sub">
				<a href="#" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-crown"></i></span>
					<span class="s-text">Dispatcher</span>
				</a>
				<ul>
					<li><a href="{{-- {{ route('admin.dispatch-manager.index') }} --}}">List Dispatcher</a></li>
					<li><a href="{{-- {{ route('admin.dispatch-manager.create') }} --}}">Add New Dispatcher</a></li>
				</ul>
			</li> -->
			<!-- <li class="with-sub">
				<a href="#" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-crown"></i></span>
					<span class="s-text">Fleet Owner</span>
				</a>
				<ul>
					<li><a href="{{-- {{ route('admin.fleet.index') }} --}}">List Fleets</a></li>
					<li><a href="{{-- {{ route('admin.fleet.create') }} --}}">Add New Fleet Owner</a></li>
				</ul>
			</li> -->
			{{-- <li class="with-sub">
				<a href="#" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-crown"></i></span>
					<span class="s-text">Account Manager</span>
				</a>
				<ul>
					<li><a href="{{ route('admin.account-manager.index') }}">List Account Managers</a></li>
					<li><a href="{{ route('admin.account-manager.create') }}">Add New Account Manager</a></li>
				</ul>
			</li> --}}

			{{-- <li class="menu-title">Accounts</li>
			<li class="with-sub">
				<a href="javascript:void(0)" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-crown"></i></span>
					<span class="s-text">Statements</span>
				</a>
				<ul>
					<li><a href="{{ route('admin.package.sales.report') }}">Package Sales Report</a></li>
					<li><a href="{{ route('admin.statement.driver.index') }}">Driver Statement</a></li>
					<li><a href="{{ route('admin.statement','overall') }}">Overall Ride Statments</a></li>
					<li><a href="{{ route('admin.statement','today') }}">Daily Statement</a></li>
					<li><a href="{{ route('admin.statement','weekly') }}">Weekly Statement</a></li>
					<li><a href="{{ route('admin.statement','monthly') }}">Monthly Statement</a></li>
					<li><a href="{{ route('admin.statement','yearly') }}">Yearly Statement</a></li>
				</ul>
			</li> --}}
			
			{{-- <li class="menu-title">Details</li>
			<li>
				<a href="{{ route('admin.map.index') }}" class="waves-effect waves-light">
					<span class="s-icon"><i class="ti-map-alt"></i></span>
					<span class="s-text">Map</span>
				</a>
			</li>
			
			
			<li>
				<a href="{{ route('admin.requests.scheduled') }}" class="waves-effect  waves-light">
					<span class="s-icon"><i class="ti-palette"></i></span>
					<span class="s-text">Scheduled Rides</span>
				</a>
			</li> --}}

			<li class="menu-title">General</li>
			{{-- <li class="with-sub">
				<a href="#" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-crown"></i></span>
					<span class="s-text">Vehicle</span>
				</a>
				<ul>
					<li><a href="{{ route('admin.vehicle.index') }}">List Vehicles</a></li>
					<li><a href="{{ route('admin.vehicle.create') }}">Add New Vehicle</a></li>
				</ul>
			</li> --}}
			{{-- 
			<li class="with-sub">
				<a href="javascript:void(0)" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-view-grid"></i></span>
					<span class="s-text">Service Types</span>
				</a>
				<ul>
					<li><a href="{{ route('admin.service.index') }}">List Service Types</a></li>
					<li><a href="{{ route('admin.service.create') }}">Add New Service Type</a></li>
				</ul>
			</li> --}}
			<li class="with-sub">
				<a href="javascript:void(0)" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-layout-tab"></i></span>
					<span class="s-text">Documents</span>
				</a>
				<ul>
					<li><a href="{{ route('admin.document.index') }}">List Documents</a></li>
					<li><a href="{{ route('admin.document.create') }}">Add New Document</a></li>
				</ul>
			</li>

			{{-- <li class="with-sub">
				<a href="javascript:void(0)" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-layout-tab"></i></span>
					<span class="s-text">Credit Package</span>
				</a>
				<ul>
					<li><a href="{{ route('admin.credit.index') }}">List Credit Package</a></li>
				</ul>
			</li> --}}

			{{-- <li class="with-sub">
				<a href="javascript:void(0)" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-layout-tab"></i></span>
					<span class="s-text">Email Control</span>
				</a>
				<ul>
					<li><a href="{{ route('admin.email-control.index') }}">List Email Control</a></li>
				</ul>
			</li> --}}

			{{-- <li class="with-sub">
				<a href="#" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="fa fa-map-marker"></i></span>
					<span class="s-text">Locations' Fee</span>
				</a>
				<ul>
					<li><a href="{{ route('admin.locationfee.index') }}">List Locations</a></li>
					<li><a href="{{ route('admin.locationfee.create') }}">Add New Locations</a></li>
				</ul>
			</li> --}}

                        {{-- <li class="with-sub">
				<a href="#" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="fa fa-map-marker"></i></span>
					<span class="s-text">Send Airport Instruction</span>
				</a>
				<ul>
					<li><a href="{{ route('admin.airportinstructionpush.index') }}">List Airport Instruction</a></li>
					<li><a href="{{ route('admin.airportinstructionpush.create') }}">Add Airport Instruction</a></li>
				</ul>
			</li> --}}
                        
			{{-- <li class="with-sub">
				<a href="#" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="fa fa-newspaper-o"></i></span>
					<span class="s-text">News And Events</span>
				</a>
				<ul>
					<li><a href="{{ route('admin.newsandevent.index') }}">List News And Events</a></li>
					<li><a href="{{ route('admin.newsandevent.create') }}">Add News or Event</a></li>
				</ul>
			</li> --}}

			{{-- <li class="with-sub">
				<a href="#" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-layout-tab"></i></span>
					<span class="s-text">Promocodes</span>
				</a>
				<ul>
					<li><a href="{{ route('admin.promocode.index') }}">List Promocodes</a></li>
					<li><a href="{{ route('admin.promocode.create') }}">Add New Promocode</a></li>
				</ul>
			</li> --}}
			{{-- <li class="with-sub">
				<a href="#" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-layout-tab"></i></span>
					<span class="s-text">Report Issues</span>
				</a>
				<ul>
					<li><a href="{{ route('admin.report-issue.bydriver') }}">Reported By Driver</a></li>
					<li><a href="{{ route('admin.report-issue.bypassenger') }}">Reported By Passenger</a></li>
				</ul>
			</li> --}}
			
			{{-- <li class="with-sub">
				<a href="#" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-layout-tab"></i></span>
					<span class="s-text">Promotions</span>
				</a>
				<ul>
					<li><a href="{{ route('admin.promotion.index') }}">List Promotions</a></li>
					<li><a href="{{ route('admin.promotion.create') }}">Add New Promotion</a></li>
				</ul>
			</li> --}}

			{{-- <li class="menu-title">Payment Details</li>
			<li>
				<a href="{{ route('admin.payment.index') }}" class="waves-effect  waves-light">
					<span class="s-icon"><i class="ti-infinite"></i></span>
					<span class="s-text">Payment History</span>
				</a>
			</li> --}}
			{{-- <li>
				<a href="{{ route('admin.settings.payment') }}" class="waves-effect  waves-light">
					<span class="s-icon"><i class="ti-money"></i></span>
					<span class="s-text">Payment Settings</span>
				</a>
			</li> --}}
			<li class="menu-title">Settings</li>
			<li>
				<a href="{{ route('admin.setting.index') }}" class="waves-effect  waves-light">
					<span class="s-icon"><i class="ti-settings"></i></span>
					<span class="s-text">Site Settings</span>
				</a>
			</li>

			{{-- <li class="menu-title">Others</li>
			<li>
				<a href="{{ route('admin.privacy.policy') }}" class="waves-effect waves-light">
					<span class="s-icon"><i class="ti-help"></i></span>
					<span class="s-text">Privacy Policy</span>
				</a>
			</li> --}}
			
			{{-- <li>
				<a href="{{ route('admin.help') }}" class="waves-effect waves-light">
					<span class="s-icon"><i class="ti-help"></i></span>
					<span class="s-text">Help</span>
				</a>
			</li>
			<li>
				<a href="{{route('admin.translation') }}" class="waves-effect waves-light">
					<span class="s-icon"><i class="ti-smallcap"></i></span>
					<span class="s-text">Translations</span>
				</a>
			</li> --}}
			<li class="menu-title">Account</li>
			<li>
				<a href="{{ route('admin.profile') }}" class="waves-effect  waves-light">
					<span class="s-icon"><i class="ti-user"></i></span>
					<span class="s-text">Account Settings</span>
				</a>
			</li>
			<li>
				<a href="{{ route('admin.password') }}" class="waves-effect  waves-light">
					<span class="s-icon"><i class="ti-exchange-vertical"></i></span>
					<span class="s-text">Change Password</span>
				</a>
			</li>
			<li class="compact-hide">
				<a href="{{ url('/admin/logout') }}"
                            onclick="event.preventDefault();
                                     document.getElementById('logout-form').submit();">
					<span class="s-icon"><i class="ti-power-off"></i></span>
					<span class="s-text">Logout</span>
                </a>

                <form id="logout-form" action="{{ url('/admin/logout') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                </form>
			</li>
			
		</ul>
	</div>
</div>