routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/login', 'Admin\Auth\LoginController@showLoginForm')->name('/login');
Route::get('/', 'Admin\Auth\LoginController@showLoginForm')->name('/');
Route::post('/loggedin', 'Admin\Auth\LoginController@login');
Route::get('/password/reset', 'Admin\Auth\ForgotPasswordController@otpRequestForm')->name('password.reset');
Route::post('password/email', 'Admin\Auth\ForgotPasswordController@sendOTP')->name('password.email');
Route::get('password/otp', 'Admin\Auth\ForgotPasswordController@otpForm')->name('password.otp');
Route::get('password/otpvarify', 'Admin\Auth\ForgotPasswordController@otpVarification')->name('password.otpvarify');
Route::get('password/edit', 'Admin\Auth\ForgotPasswordController@passworUpdateForm')->name('password.edit');
Route::post('password/update', 'Admin\Auth\ForgotPasswordController@updatePassword')->name('password.update');

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {

	Route::post('logout', 'Auth\LoginController@logout')->name('logout');
	Route::resource('dashboard', 'Dashboard\DashboardController');

	Route::get('password', 'AdminController@password')->name('password');
	Route::post('password/update', 'AdminController@changePassword')->name('password.update');

	Route::get('profile', 'AdminController@profile')->name('profile');
	Route::post('profile/update', 'AdminController@profileUpdate')->name('profile.update');

	Route::resource('setting', 'Setting\SettingController');
	// Route::get('privacy/policy', 'Setting\SettingController@privacyPolicy')->name('privacy.policy');
	// Route::put('privacy-policy/update/{id}', 'Setting\SettingController@privacyPolicyUpdate')->name('privacy-policy.update');

	Route::resource('document', 'Document\DocumentController');
	Route::get('document/active/{id}', 'Document\DocumentController@changeStatus')->name('document.active');

	// Route::resource('service', 'Service\ServiceTypeController');

	// Route::resource('vehicle', 'Vehicle\VehicleController');
	// Route::post('vehicles','Vehicle\VehicleController@getVehicles')->name('dataProcessing');

	Route::resource('passenger', 'Passenger\PassengerController');
	Route::post('ajax-passenger','Passenger\PassengerController@ajaxPassenger')->name('ajax-passenger');

	Route::resource('driver', 'Driver\DriverController');
	Route::post('ajax-driver','Driver\DriverController@ajaxDriver')->name('ajax-driver');

	Route::get('drivers/document/{id}', 'Driver\DriverController@listDriverDocument')->name('drivers.document');
	// Route::get('drivers/service-type/{id}', 'Driver\DriverController@listDriverServiceType')->name('drivers.service-type');
	Route::get('driver/document/verification/{id}', 'Driver\DriverController@driverDocumentVerification')->name('driver.document.verification');
	Route::get('driver/activation/{id}', 'Driver\DriverController@driverActivationProcess')->name('driver.activation');
	// Route::get('driver/carimages/{id}', 'Driver\DriverController@driverCarImages')->name('driver.carimages');
	// Route::get('driver/transaction/{id}', 'Driver\DriverController@driverTransaction')->name('driver.transaction');
	// Route::post('driver/document-reason/{id}', 'Driver\DriverController@documentVerificationReason')->name('driver.document-reason');

	// Route::resource('credit', 'CreditPackage\CreditPackageController');
	// Route::resource('email-control', 'Email\EmailController');

	// //Driver Document verification.........

	// Route::get('driver/check-document/{id}', 'Driver\DocumentVerificationController@allDocumentCheck')->name('driver.check-document');
	// Route::get('driver/rating-review/{id}', 'Driver\DriverRatingController@driverRatingReview')->name('driver.rating-review');
	// Route::get('driver/runcron/{id}', 'Driver\DocumentVerificationController@cronjobToMailDriver')->name('driver.runcron');
	// //.....................................

	// Route::get('driver/rating-list/{id}/{last_id}/{first_id}', 'Driver\DriverRatingController@ratingList')->name('driver.rating-list');
	// Route::post('driver/reason/{id}', 'Driver\DriverController@driverInactiveBannedReason')->name('driver.reason');
	// Route::get('driver/rating-search/{id}', 'Driver\DriverRatingController@searchRating')->name('driver.rating-search');

	// Route::post('driver/rating-alert/{id}', 'Driver\DriverRatingController@driverRatingAlert')->name('driver.rating-alert');
	// //payment

	// Route::get('payment/index', 'Payment\PaymentController@paymentList')->name('payment.index');

	// Route::get('package/sales/report', 'PackageSales\PackageSalesReportController@packageSalesReport')->name('package.sales.report');
	// Route::get('package/sales/report/search', 'PackageSales\PackageSalesReportController@searchPackageSalesReport')->name('package.sales.report.search');
	// Route::get('package/sales/report/details/{id}', 'PackageSales\PackageSalesReportController@packageSalesReportDetails')->name('package.sales.report.details');
	// Route::get('package/sales/report/detail/{id}/{from_date}/{to_date}', 'PackageSales\PackageSalesReportController@packageSalesReportDetailsBySearch')->name('package.sales.report.detail');

	// //ride history
	// Route::get('statement/{type}', 'Statement\StatementController@statement')->name('statement');
	// 	//not use
	// 	Route::get('statement/today', 'Statement\StatementController@statement_today')->name('statement.today');
	// 	Route::get('statement/weekly', 'Statement\StatementController@statement_weekly')->name('statement.weekly');
	// 	Route::get('statement/monthly', 'Statement\StatementController@statement_monthly')->name('statement.monthly');
	// 	Route::get('statement/yearly', 'Statement\StatementController@statement_yearly')->name('statement.yearly');
	// 	//not use
	// Route::post('ajax-statement','Statement\StatementController@ajaxStatement')->name('ajax-statement');
	// //............

	// Route::get('statement/details/{id}/{param}', 'Statement\StatementController@rideDetails')->name('statement.details');

	// Route::get('statement/driver/index', 'Statement\StatementController@driverStatementIndex')->name('statement.driver.index');
	// Route::post('ajax-driver-statement','Statement\StatementController@ajaxDriverStatement')->name('ajax-driver-statement');

	// Route::get('statement/driver/details/{id}', 'Statement\StatementController@driverStatementDetails')->name('statement.driver.details');
	// Route::get('statement/driver/detailsbybid/{id}', 'Statement\StatementController@driverStatementDetailsByBid')->name('statement.driver.detailsbybid');
	
	// Route::resource('promocode', 'Promocode\PromocodeController');

	// Route::get('report-issue/bydriver', 'ReportIssue\ReportIssueController@reportedByDriver')->name('report-issue.bydriver');
	// Route::get('report-issue/bypassenger', 'ReportIssue\ReportIssueController@reportedByPassenger')->name('report-issue.bypassenger');
	// Route::get('report-issue/details/{id}/{param}', 'ReportIssue\ReportIssueController@reportIssueDetails')->name('report-issue.details');

	

});

app/Http/Controllers/Admin/Driver/DriverController.php
<?php

namespace App\Http\Controllers\Admin\Driver;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\Profiles\DriverProfiles;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Exception;
use App\User;
// use App\Model\Driver\DriverServices;
// use App\Model\ServiceType;
use App\Model\Document\DriverDocuments;
use App\Model\Document\Document;
use App\Model\Driver\DriverCarImages;
use App\Http\Controllers\Api\Transaction\TransactionController;
use Illuminate\Support\Facades\Notification;
use App\Notifications\EmailNotification;
use App\Model\Driver\DriverDocumentReason;
use App\Model\Driver\DriverReason;

use App\Model\ServiceType\DriverServiceType;
use App\Services\ServiceTypeMst;

use App\Services\DriversProfileService;



class DriverController extends Controller
{
   
    public function index()
    {
        return view('admin.driver.index');
    }

    public function ajaxDriver(Request $request)
    {
        $columns = array(
            0 => 'first_name',
            1 => 'email_id',
            2 => 'isd_code',
        );
        
        $totalData =  User::where('user_scope', 'driver-service')->count();
        $limit = $request->input('length');
        $limit = (integer)$limit;
        $start = $request->input('start');
        $order = $columns[$request->input('order.0.column')];
        $dir = $request->input('order.0.dir');
        if ($dir == 'asc') {
            $dir = 1;
        } else {
            $dir = -1;
        }

        if(empty($request->input('search.value'))){
            $drivers = User::where('user_scope', 'driver-service')
                ->get();
            foreach ($drivers as $key => $driver) {
                $df = DriverProfiles::where('user_id',$driver->_id)
                    ->offset($start)
                    ->limit($limit)
                    ->orderBy($order,$dir)
                    ->first();
                $driver->first_name = $df->first_name;
                $driver->last_name  = $df->last_name;
                $driver->email_id   = $df->email_id;
                $driver->mobile_no  = $df->mobile_no;
                $driver->isd_code   = $df->isd_code;
                $driver->service_status   = $df->service_status;
            }
            
            $totalFiltered = User::where('user_scope', 'driver-service')->count();
        }else{
            $search = $request->input('search.value');
            $drivers = DriverProfiles::where(function($q) use ($search){
                        $q->where('first_name', 'like', "%{$search}%")
                        ->orWhere('last_name','like',"%{$search}%")
                        ->orWhere('email_id','like',"%{$search}%")
                        ->orWhere('isd_code','like',"%{$search}%")
                        ->orWhere('mobile_no','like',"%{$search}%");
                    })
                    ->offset($start)
                    ->limit($limit)
                    ->orderBy($order, $dir)
                    ->get();
            
            foreach ($drivers as $key => $driver) {
                $user = User::where('_id', $driver->user_id)->first();
                $driver->_id = $user->_id;
                $driver->username = $user->username;  
            }
            
            $totalFiltered = DriverProfiles::where(function($q) use ($search){
                    $q->where('first_name', 'like', "%{$search}%")
                    ->orWhere('last_name','like',"%{$search}%")
                    ->orWhere('email_id','like',"%{$search}%")
                    ->orWhere('isd_code','like',"%{$search}%")
                    ->orWhere('mobile_no','like',"%{$search}%");
                })
                ->count();
        }       

        $data = array();

        if($drivers){
            foreach($drivers as $d){
                if (isset($d->service_status)) {
                    if($d->service_status == "inactive" || $d->service_status == "block"){
                        $activationButton = '<a href="driver/activation/'.$d->id.'" class="btn btn-danger driver-status" data-toggle="tooltip" data-value="Activate" data-id="'.$d->id.'" title="Click to Active">Inactive</a>';
                    }else{
                        $activationButton = '<a href="driver/activation/'.$d->id.'" class="btn btn-success driver-status" data-toggle="tooltip" data-value="Inactivate" data-id="'.$d->id.'" title="Click to Inactive">Active</a>';
                    }
                }else{
                    $activationButton = null;
                }

                // $nestedData['id']     = $d->_id;
                $nestedData['driver_name']   = $d->first_name." ".$d->last_name;
                $nestedData['email']   = $d->username;
                $nestedData['mobile']  = $d->isd_code.'-'.$d->mobile_no;
                $nestedData['action'] = '<span style="line-height: 33px;"><a href="driver/'.$d->_id.'/edit" class="btn btn-info"><i class="fa fa-pencil"></i> Edit</a> <a href="drivers/document/'.$d->_id.'" class="btn btn-info"><i class="fa fa-file"></i> Document</a>' .$activationButton.'</span>';
                    
                    // <a href="driver/carimages/'.$d->id.'" class="btn btn-info"><i class="fa fa-file"></i> Car Images</a>
                    // <a href="driver/transaction/'.$d->id.'" class="btn btn-info"><i class="fa fa-file"></i> Package</a>

                    // <a href="drivers/service-type/'.$d->_id.'" class="btn btn-info"><i class="fa fa-file"></i> Service</a>

                $data[] = $nestedData;
            }
        }
        
        $json_data = array(
            "draw"            => intval($request->input('draw')),
            "recordsTotal"    => intval($totalData),
            "recordsFiltered" => intval($totalFiltered),
            "data"            => $data
        );
        
        echo json_encode($json_data);
    }

    public function listDriverServiceType($id)
    {
        try{
            $ServiceType=DriverServiceType::select('user_id','service_type_id','registration_no','registration_expire','model','vechile_identification_no','driver_service_type_id','updated_at','created_at')->where("user_id",$id)->first();
            if (isset($ServiceType)){
                $ServiceTypeMst=new ServiceTypeMst();
                $ServiceTypeMstData=$ServiceTypeMst->accessGetNameByID($ServiceType);
                $ServiceType->serviceName=$ServiceTypeMstData->name;
                return view('admin.driver.service',compact('ServiceType'));
            } else {
                 return redirect()->back()->with('flash_error', 'Service type not found!');
            }
        }
        catch(\Illuminate\Database\QueryException  $e){
            return redirect()->back()->with('flash_error', 'Something went wrong!');
        }
        catch(\Illuminate\Http\Exceptions\HttpResponseException $e){
            return redirect()->back()->with('flash_error', 'Something went wrong!');
        }
        catch(ModelNotFoundException $e){
            return redirect()->back()->with('flash_error', 'You are not registered with us!');
        }
    }
  
    public function create()
    {
        return view('admin.driver.create');
    }

    public function store(Request $request)
    {
        try{
            $this->validate($request, [
                'first_name'        => 'required|max:255',
                'last_name'         => 'required|max:255',
                'email'             => 'required|email|max:255|unique:users,username',
                'picture'           => 'mimes:jpeg,jpg,bmp,png|max:5242880',
                'password'          => 'required|confirmed|min:6',
                'mobile'            => 'required|regex:/^([0-9\s\-\+\(\)]*)$/|min:6|max:16|unique:drivers_profile,mobile_no'
            ]);
            
            if (empty($request->mobile)) {
                $request->code = null;
            } else {
                $request->code = '+'.$request->code;
            }
            // creating new users
            $User = new User();
            $User->password=bcrypt(trim($request->password));
            $User->user_scope="driver-service";
            $User->username=$request->email;
            $User->save();

            $DriverProfiles=new DriverProfiles();
            $DriverProfiles->user_id=$User->_id;
            $DriverProfiles->first_name=$request->first_name;
            $DriverProfiles->last_name=$request->last_name;
            $DriverProfiles->email_id = $request->email;
            if(isset($request->picture) && !empty($request->picture)){
                $picture = $request->picture->store('public/driver/profile');
                $picture = str_replace("public", "storage", $picture);
                $DriverProfiles->picture=$picture;
            }
            $DriverProfiles->mobile_no=$request->mobile;
            $DriverProfiles->isd_code=$request->code;
            $DriverProfiles->dob=$request->dob;
            $DriverProfiles->gender=$request->gender;

            $DriverProfiles->save();
            
            if(!empty($User)){

                if($User->_id>0){
                    return redirect()->back()->with('flash_success', 'Thank you for registering with us!');
                }
            }
            return redirect()->back()->with('flash_error', 'Registration not possible!');
        }

        catch(\Illuminate\Database\QueryException  $e){
            return redirect()->back()->with('flash_error', 'Something went wrong!');
        }
        catch(\Illuminate\Http\Exceptions\HttpResponseException $e){
            return redirect()->back()->with('flash_error', 'Something went wrong!');
        }

    }

   
    public function show($id)
    {
        //
    }

    
    public function edit(Request $request,$id)
    {
        try {
            $driver = User::find($id);
            $Profile=new DriversProfileService();
            $request->user_id = $id;

app/Http/Controllers/Api/Driver/EmergencyContactController.php
<?php

resources/views/admin/driver/carimage.blade.php
@extends('admin.layout.base')

@section('title', 'Car Images')

@section('content')
<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            <h5 class="mb-1">Car Images</h5>
            <a href="{{ route('admin.driver.index') }}" style="margin-left: 1em;" class="btn btn-primary pull-right"><i class="fa fa-angle-left"></i> Back</a>
            <table class="table table-striped table-bordered dataTable" id="table-carimage">
                <thead>
                    <tr>
                        <th>S.No</th>
                        <th>Car Image</th>
                    </tr>
                </thead>
                <tbody>
                @foreach($carimages as $index => $carimage)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>
                            @if(isset($carimage->image_url))
                                @if(File::exists(storage_path('app/public' .str_replace("storage", "", $carimage->image_url))))
                                    <img src="{{URL::asset($carimage->image_url)}}" style="height: 200px; width: 250px;">
                                @else
                                    <img src="{{URL::asset('asset/NO_IMG.png')}}" style="height: 50px; width: 65px;">
                                @endif
                            @else
                                <img src="{{URL::asset('asset/NO_IMG.png')}}" style="height: 50px; width: 65px;">
                            @endif
                        </td>
                    </tr>
                @endforeach
                </tbody>
                <tfoot>
                    <tr>
                        <th>S.No</th>
                        <th>Car Image</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>
@endsection
@section('scripts')
<script>
$(document).ready(function(){
    $('#table-carimage').DataTable( {
        responsive: true,
        dom: 'Bfrtip',
        buttons: []
    } );
});
</script>
@endsection

resources/views/admin/driver/index.blade.php
@extends('admin.layout.base')

@section('title', 'Drivers ')

@section('content')
<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            <h5 class="mb-1">
                Drivers
            </h5>
            <a href="{{ route('admin.driver.create') }}" style="margin-left: 1em;" class="btn btn-primary pull-right"><i class="fa fa-plus"></i> Add New Driver</a>
            <table class="table table-hover table-striped table-bordered dataTable" id="table-driv">
                <thead>
                    <tr>
                        {{-- <th>ID</th> --}}
                        <th>Driver Name</th>
                        {{-- <th>Last Name</th> --}}
                        <th>Email</th>
                        <th>Mobile</th>
                        {{--  <th>Avg Rating</th> --}}
                        <th>Action</th>
                    </tr>
                </thead>
               {{--  <tbody>
                    @foreach($drivers as $index => $driver)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>{{ $driver->first_name }}</td>
                        <td>{{ $driver->last_name }}</td>
                        <td>{{ $driver->email }}</td>
                        <td>{{ $driver->mobile }}</td>
                        @if($driver->driver_profile != null)
                        <td>{{ $driver->driver_profile->rating }}</td>
                        @else
                        <td></td>
                        @endif --}}
                        {{-- @if($driver->passenger_request!=null)
                            @php
                            $totalRating = null;
                            @endphp
                            @foreach($driver->passenger_request as $index => $passenger_request)
                            @php
                            $totalRating = $totalRating+$passenger_request->driver_rating;
                            $index++;
                            @endphp
                            @endforeach
                            <td>{{round($totalRating/$index,2)}}</td>
                        @else
                            <td></td>
                        @endif --}}
                       {{--  <td style="line-height: 34px;">
                            <a href="{{ route('admin.driver.edit', $driver->id) }}" class="btn btn-info"><i class="fa fa-pencil"></i> Edit</a>
                            <a href="{{ route('admin.drivers.document', $driver->id) }}" class="btn btn-info"><i class="fa fa-file"></i> Document</a>
                            <a href="{{ route('admin.driver.carimages', $driver->id) }}" class="btn btn-info"><i class="fa fa-file"></i> Car Images</a>
                            @if($driver->driver_profile)
                                @if($driver->driver_profile->status == 'onboarding' || $driver->driver_profile->status == 'banned')
                                <a href="{{ route('admin.driver.activation', $driver->id) }}" class="btn btn-danger driver-status" data-toggle="tooltip" data-value="Activate" data-id="{{$driver->id}}" title="Click to Active">Inactive</a>
                                @else
                                <a href="{{ route('admin.driver.activation', $driver->id) }}" class="btn btn-success driver-status" data-toggle="tooltip" data-value="Inactivate" data-id="{{$driver->id}}" title="Click to Inactive">Active</a>
                                @endif
                            @else
                            @endif
                            <a href="{{ route('admin.driver.transaction', $driver->id) }}" class="btn btn-info"><i class="fa fa-file"></i> Package</a>

                            <a href="{{ route('admin.driver.rating-review',46) }}" class="btn btn-info"><i class="fa fa-file"></i>Rating</a>
                            
                        </td>
                    </tr>
                    @endforeach
                </tbody> --}}
                <tfoot>
                    <tr>
                        {{-- <th>ID</th> --}}
                        <th>Driver Name</th>
                        {{-- <th>Last Name</th> --}}
                        <th>Email</th>
                        <th>Mobile</th>
                        {{-- <th>Avg Rating</th> --}}
                        <th>Action</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>

{{-- ..........Document Modal................. --}}
<div class="modal fade" id="driverModel" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-md modal-dialog-centered" role="document">
    <div class="modal-content" style="background-color: lavender;">
      <div class="modal-header">
        <h5 class="modal-title"></h5>
      </div>
      <div class="modal-body">
      
        <div class="d-flex justify-content-center">
            <div class="col-lg-12">

                <div class="alert alert-danger reason-danger" role="alert" style="display: none; height: 42px;">
                    <p class="reason-error" style="color: red; padding: 0px;"></p>
                </div>

                <form>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label class="control-label text-dark">Reason</label>
                                <textarea name="reason" id="reason" rows="4" class="form-control" required></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            {{-- <input type="submit" class="btn btn-info float-left" id="saveReason" value="Submit"> --}}
                            <a href="javascript:void(0)" class="btn btn-info float-left" id="saveReason" style="width: 70px;">
                            <span id="submit">Submit</span>
                            <i id="submit_spin" class="fa fa-circle-o-notch fa-spin" style="font-size: 20px; display: none;"></i>
                            </a>
                            <a href="" class="btn btn-secondary float-right">Close</a>
                        </div>
                    </div>
                </form>
                 
            </div>
        </div>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>
{{-- end Document Modal --}}
@endsection
@section('scripts')
<script>
    $(document).ready(function(){

        $('#table-driv').DataTable( {
            //"order": [[0, 'desc']],
            "processing": true,
            "serverSide": true,
            "ajax": {
                "url":"{{route('admin.ajax-driver')}}",
                "dataType":"json",
                "type":"POST",
                "data":{"_token":"<?= csrf_token() ?>"}
            },
            "columns":[
                // {"data":"id"},
                {"data":"driver_name", "orderable":false},
                {"data":"email", "orderable":false},
                {"data":"mobile", "orderable":false},
                {"data":"action","searchable":false,"orderable":false}
            ],
            responsive: true,
            dom: 'Bfrtip',
            buttons: [
                'copyHtml5',
                'excelHtml5',
                'csvHtml5',
                'pdfHtml5'
            ],
        } );

        // $(document).on('click','.driver-status',function (e) {
        //     e.preventDefault();
        //     var href = $(this).attr('href');
        //     var value = $(this).data('value');
        //     var id = $(this).data("id");
        //     if (value == 'Activate') {
        //     bootbox.confirm('Do you really want to '+value+' driver?', function (res) {
        //     if (res){
        //         window.location = href;
        //     }  
        //     });
        //   }
        //   if (value == 'Inactivate') {
        //     $('#driverModel').modal('show');
        //     $('.modal-title').html('Driver Inactivate');
        //     $('#saveReason').click(function(e){
        //       e.preventDefault()
        //       $.ajaxSetup({
        //         headers:{
        //           'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        //         }
        //       });
        //       var reason = $('#reason').val();
        //       $('#submit').css({'display':'none'});
        //       $('#submit_spin').css({'display':'block'});
        //       $.ajax({
        //         url: '',
        //         method: 'post',
        //         data: { id:id, reason:reason },
        //         success: function(response){
        //             if (response.success) {
        //               $('#submit').css({'display':'block'});
        //               $('#submit_spin').css({'display':'none'});
        //               $('#driverModel').modal('hide');
        //               window.location = href;
        //             }
        //         },
        //         error: function(response){
        //           $('#submit').css({'display':'block'});
        //           $('#submit_spin').css({'display':'none'});
        //           $('.reason-danger').show();
        //           $('.reason-error').html(response.responseJSON.errors.reason);
        //         }
        //       });

        //     });
        //   }

        // });

    });
</script>
@endsection

resources/views/admin/driver/service.blade.php
@extends('admin.layout.base')

@section('title', 'Service Type')

@section('content')
<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            <h5 class="mb-1">
                Service Type
            </h5>
            <a href="{{ route('admin.driver.index') }}" style="margin-left: 1em;" class="btn btn-primary pull-right"><i class="fa fa-angle-left"></i> Back</a>
            <table class="table table-striped table-bordered dataTable" id="table-2">
                <thead>
                    <tr>
                        <th>Service Name</th>
                        <th>Model</th>
                        <th>Registration No.</th>
                        <th>Vechile Identification No.</th>
                        <th>Registration Expire</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{$ServiceType['serviceName']}}</td>
                        <td>{{$ServiceType['model']}}</td>
                        <td>{{$ServiceType['registration_no']}}</td>
                        <td>{{$ServiceType['vechile_identification_no']}}</td>
                        <td>{{$ServiceType['registration_expire']}}</td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <th>Service Name</th>
                        <th>Model</th>
                        <th>Registration No.</th>
                        <th>Vechile Identification No.</th>
                        <th>Registration Expire</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>
@endsection